server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abdouvh/config-service
          search-paths: src/main/resources/micro-commandes.yml
          default-label: main
          clone-on-start: true

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG
